### ISSUE TITLE
incompatible project version

### ISSUE THREAD

**Issue by Sumenia** [warrenm/HelloVulkanMac#1]
I keep getting `Failed to load project at 'HelloVulkanMac/HelloVulkanMac.xcodeproj', incompatible project version.` when trying to open with Version 9.2 (9C40b), which version do you use ?

**Comment by warrenm** [comment]
Xcode 9.3 beta 3. I've recreated the project in Xcode 9.2 with 197e5ad. Let me know if that fixes this; thanks!

**Comment by Sumenia** [comment]
It works now, thank you ! 👍
